package com.example.ui.utils

object Localization {
    private val translations = mapOf(
        "FR" to mapOf(
            "welcome_title" to "Bienvenue sur StaffFlow",
            "welcome_subtitle" to "Plateforme intelligente de Gestion de Présence & Paie",
            "admin_access" to "Accès Administrateur",
            "employee_access" to "Accès Collaborateur",
            "welcome_desc" to "Gérez facilement vos ressources humaines, suivez les pointages par QR Code en temps réel et simplifiez le calcul de la paie.",
            
            "login_title" to "Connexion StaffFlow",
            "login_subtitle" to "Veuillez vous identifier pour continuer",
            "login_register_title" to "Créer un Compte",
            "admin_space" to "Espace Admin",
            "employee_space" to "Collaborateur",
            "username" to "Nom d'utilisateur",
            "password" to "Mot de passe",
            "connect_admin" to "Se Connecter (Admin)",
            "connect_emp" to "Accéder à Mon Espace",
            "new_admin" to "Nouveau administrateur ? Créer un compte",
            "new_emp" to "Nouveau Collaborateur ? S'enregistrer ici",
            "register_btn" to "Enregistrer Mon Compte",
            "back_login" to "Retour à la Connexion",
            
            "dashboard" to "Dashboard",
            "employees" to "Employés",
            "attendance" to "Pointage",
            "salaries" to "Salaires",
            "reports" to "Rapports",
            "settings" to "Paramètres",
            
            "overview" to "Vue d'ensemble",
            "active_emp" to "Employés Actifs",
            "present_today" to "Présents Aujourd'hui",
            "late_today" to "Retards du Jour",
            "salaries_paid" to "Salaires Versés",
            
            "trend_title" to "Tendance des Pointages (Semaine)",
            "recent_scans" to "Derniers Pointages Réalisés",
            "no_scans" to "Aucun pointage enregistré pour le moment aujourd'hui.",
            "logout" to "Déconnexion",
            
            "lang_select" to "Langue",
            "lang_desc" to "Sélectionnez votre langue de préférence pour l'application.",
            "theme_select" to "Thème Visuel",
            "theme_desc" to "Forcer le mode sombre ou utiliser les paramètres système.",
            "currency" to "Devise d'affichage",
            "currency_desc" to "Devise utilisée pour l'affichage des salaires et bonus.",
            "about" to "À propos",
            "version" to "Version 2.4 (Ariary Edition)",
            "developer" to "Développé pour la gestion d'entreprise intelligente.",
            "sec_title" to "Sécurité",
            "sec_desc" to "Générer un rapport de sécurité ou réinitialiser les caches.",
            "lang_fr" to "Français",
            "lang_en" to "English",
            "lang_mg" to "Malagasy",
            "my_qr" to "Mon QR",
            "pointages_tab" to "Pointages",
            "my_salary_tab" to "Mon Salaire",
            "theme_system" to "Système",
            "theme_light" to "Clair",
            "theme_dark" to "Sombre",
            "sync_title" to "Synchronisation Multi-Appareils (Option 1)",
            "sync_desc" to "Partagez et synchronisez les employés, pointages et salaires en temps réel entre plusieurs téléphones ou tablettes via une API Cloud commune.",
            "sync_enable" to "Activer la Synchronisation Cloud",
            "sync_url" to "URL du Serveur API",
            "sync_key" to "Clé d'authentification API (Token)",
            "sync_now" to "Synchroniser Maintenant",
            "sync_status_label" to "Statut de Synchronisation",
            "sync_last" to "Dernière sync réussie",
            "local_server_title" to "Serveur Wi-Fi Local (Option 1 - Recommandé)",
            "local_server_desc" to "Transformez cet appareil de bureau en mini-serveur local sans abonnement cloud. Les téléphones des employés s'y connecteront en Wi-Fi pour envoyer instantanément leurs heures de pointage.",
            "local_server_enable" to "Héberger le Serveur de Pointage",
            "local_server_ip" to "IP de l'Hôte",
            "local_server_port" to "Port Réseau",
            "local_server_logs" to "Historique en direct du serveur local",
            "local_server_no_logs" to "En attente de connexions d'employés...",
            "client_server_ip" to "Adresse IP du serveur Admin",
            "client_server_port" to "Port du serveur Admin",
            "client_wifi_pointage" to "Enregistrer Pointage via Wi-Fi"
        ),
        "EN" to mapOf(
            "welcome_title" to "Welcome to StaffFlow",
            "welcome_subtitle" to "Intelligent Attendance & Payroll Management Platform",
            "admin_access" to "Administrator Access",
            "employee_access" to "Employee Access",
            "welcome_desc" to "Easily manage your human resources, track QR Code attendances in real time, and simplify payroll calculations.",
            
            "login_title" to "StaffFlow Sign In",
            "login_subtitle" to "Please authenticate to continue",
            "login_register_title" to "Create Account",
            "admin_space" to "Admin Area",
            "employee_space" to "Employee",
            "username" to "Username",
            "password" to "Password",
            "connect_admin" to "Sign In (Admin)",
            "connect_emp" to "Access My Space",
            "new_admin" to "New administrator? Create an account",
            "new_emp" to "New Employee? Register here",
            "register_btn" to "Register My Account",
            "back_login" to "Back to Login",
            
            "dashboard" to "Dashboard",
            "employees" to "Employees",
            "attendance" to "Attendance",
            "salaries" to "Salaries",
            "reports" to "Reports",
            "settings" to "Settings",
            
            "overview" to "Overview",
            "active_emp" to "Active Employees",
            "present_today" to "Present Today",
            "late_today" to "Late Today",
            "salaries_paid" to "Salaries Issued",
            
            "trend_title" to "Weekly Scanning Trend",
            "recent_scans" to "Latest Scans Logged",
            "no_scans" to "No scanners logged yet for today.",
            "logout" to "Log Out",
            
            "lang_select" to "Language",
            "lang_desc" to "Select your language of preference for the application screens.",
            "theme_select" to "Visual Theme",
            "theme_desc" to "Configure light theme, dark theme, or stick with system settings.",
            "currency" to "Display Currency",
            "currency_desc" to "Currency code utilized in rendering salaries.",
            "about" to "About",
            "version" to "Version 2.4 (Ariary Edition)",
            "developer" to "Engineered for high efficiency workspace optimization.",
            "sec_title" to "Security",
            "sec_desc" to "Generate structural security assessment logs or wipe cache.",
            "lang_fr" to "Français",
            "lang_en" to "English",
            "lang_mg" to "Malagasy",
            "my_qr" to "My QR Badge",
            "pointages_tab" to "Attendances",
            "my_salary_tab" to "My Pay slips",
            "theme_system" to "System",
            "theme_light" to "Light",
            "theme_dark" to "Dark",
            "sync_title" to "Multi-Device Synchronization (Option 1)",
            "sync_desc" to "Share and synchronize employees, scans, and salaries in real-time across multiple phones/tablets via a shared Cloud API.",
            "sync_enable" to "Enable Cloud Sync",
            "sync_url" to "API Server URL",
            "sync_key" to "API Authentication Key (Token)",
            "sync_now" to "Sync Now",
            "sync_status_label" to "Sync Status",
            "sync_last" to "Last successful sync",
            "local_server_title" to "Local Wi-Fi Server (Option 1 - Recommended)",
            "local_server_desc" to "Turn this admin device into a mini local server with no subscription fees. Employees' devices will connect over Wi-Fi to log their attendance instantly.",
            "local_server_enable" to "Host Local Check-In Server",
            "local_server_ip" to "Host IP",
            "local_server_port" to "Network Port",
            "local_server_logs" to "Live server connection logs",
            "local_server_no_logs" to "Awaiting employee connections...",
            "client_server_ip" to "Admin Server IP Address",
            "client_server_port" to "Admin Server Port",
            "client_wifi_pointage" to "Register Attendance via Wi-Fi"
        ),
        "MG" to mapOf(
            "welcome_title" to "Tonga soa eto amin'ny StaffFlow",
            "welcome_subtitle" to "Sehatra fanaovana Pointage & Fitantanana Karama",
            "admin_access" to "Fidirana Mpandraharaha",
            "employee_access" to "Fidirana Mpiara-miasa",
            "welcome_desc" to "Tantano mora foana ny mpiasa, araho amin'ny alalan'ny QR Code ny fahatongavana, ary tsory ny fikajiana ny karama.",
            
            "login_title" to "Fidirana StaffFlow",
            "login_subtitle" to "Mampidira solonanarana sy teny miafina mba hanohizana",
            "login_register_title" to "Hoforonina ny Kaonty",
            "admin_space" to "Toeran'ny Admin",
            "employee_space" to "Mpiara-miasa",
            "username" to "Solonanarana",
            "password" to "Teny miafina",
            "connect_admin" to "Hiditra (Admin)",
            "connect_emp" to "Hiditra amin'ny Toerako",
            "new_admin" to "Admin vaovao? Mamorona kaonty eto",
            "new_emp" to "Mpiara-miasa vaovao? Misoratra anarana eto",
            "register_btn" to "Hisoratra Anarana",
            "back_login" to "Hiverina hiditra",
            
            "dashboard" to "Daba",
            "employees" to "Mpiasa",
            "attendance" to "Pointage",
            "salaries" to "Karama",
            "reports" to "Tatitra",
            "settings" to "Fikirakirana",
            
            "overview" to "Topi-maso ankapobeny",
            "active_emp" to "Mpiasa Mavitrika",
            "present_today" to "Tonga Androany",
            "late_today" to "Tonga Tara Androany",
            "salaries_paid" to "Karama Voaloha",
            
            "trend_title" to "Fironan'ny Pointage (Herinandro)",
            "recent_scans" to "Pointage Farany Androany",
            "no_scans" to "Mbola tsy misy pointage voasoratra androany.",
            "logout" to "Hiala",
            
            "lang_select" to "Teny",
            "lang_desc" to "Safidio ny teny tianao hisehoan'ny fampiharana.",
            "theme_select" to "Endrika",
            "theme_desc" to "Safidio ny endrika mazava na maizina.",
            "currency" to "Vola ampiasaina",
            "currency_desc" to "Ny solovola hanehoana ny karama sy tambiny.",
            "about" to "Momba ny fampiharana",
            "version" to "Version 2.4 (Edisiona Ariary)",
            "developer" to "Namboarina ho amin'ny fitantanana orinasa maranitra.",
            "sec_title" to "Fiarovana",
            "sec_desc" to "Hamoaka tatitra momba ny fiarovana na hanafaka cache.",
            "lang_fr" to "Français",
            "lang_en" to "English",
            "lang_mg" to "Malagasy",
            "my_qr" to "QR-ko",
            "pointages_tab" to "Pointages-ko",
            "my_salary_tab" to "Karamako",
            "theme_system" to "Manaraka System",
            "theme_light" to "Mazava",
            "theme_dark" to "Maizina",
            "sync_title" to "Fampifanarahana Masinina Maro (Option 1)",
            "sync_desc" to "Mizara sy mampifanaraka mpiasa, pointage ary karama mivantana amin'ny finday maro amin'ny alalan'ny Cloud API iraisana.",
            "sync_enable" to "Hampandeha ny Cloud Sync",
            "sync_url" to "Lien Server API",
            "sync_key" to "Teny miafina API (Token)",
            "sync_now" to "Hampifanaraka Izao",
            "sync_status_label" to "Fandrosoana fampifanarahana",
            "sync_last" to "Fampifanarahana farany vitany",
            "local_server_title" to "Server Wi-Fi Antoerana (Safidy 1 - Tsara indrindra)",
            "local_server_desc" to "Hampandeha ity fitaovana ity ho mini-server pointage tsy misy sarany. Ny findain'ny mpiasa dia hifandray amin'ny Wi-Fi handefasana pointage avy hatrany.",
            "local_server_enable" to "Hampiantrano ny Server Pointage",
            "local_server_ip" to "IP fitaovana",
            "local_server_port" to "Port an'ny Server",
            "local_server_logs" to "Lisitry ny fandefasana pointage mivantana",
            "local_server_no_logs" to "Miandry mpiasa hifandray...",
            "client_server_ip" to "Lien IP an'ny server Admin",
            "client_server_port" to "Port an'ny server Admin",
            "client_wifi_pointage" to "Hanao Pointage amin'ny Wi-Fi"
        )
    )

    fun get(key: String, lang: String): String {
        return translations[lang]?.get(key) ?: translations["FR"]?.get(key) ?: key
    }
}
